CREATE TABLE BOARD
(
    "BOARD_NUM" NUMBER, 
	"BOARD_NAME" VARCHAR2(20 BYTE), 
	"BOARD_PASS" VARCHAR2(15 BYTE), 
	"BOARD_SUBJECT" VARCHAR2(50 BYTE), 
	"BOARD_CONTENT" VARCHAR2(2000 BYTE), 
	"BOARD_FILE" VARCHAR2(50 BYTE), 
	"BOARD_DATE" DATE
)